version: '3.8'

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: labo-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443:443'
    networks:
      kevin-network:
  mongodb:
    image: mongo:latest
    container_name: labo-mongodb
    hostname: mongodb
    volumes:
      - ./apps/mongodb/init/:/docker-entrypoint-initdb.d/:ro
      - ./apps/mongodb/data/db/:/data/db/
      - ./apps/mongodb/data/log/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: test
    ports:
      - '28017:28017'
    command: mongod --port 28017
    networks:
      kevin-network:
  server1:
    build: ./
    container_name: labo-server1
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=shortener.net
      - VIRTUAL_PORT=3333
    ports:
      - '3333:3333'
    depends_on:
      - mongodb
    networks:
      kevin-network:
  sonarqube:
    container_name: labo-sonarqube
    image: sonarqube:latest
    environment:
      - VIRTUAL_HOST=sonar.net
      - VIRTUAL_PORT=9000
    ports:
      - '9080:9000'
    networks:
      kevin-network:
networks:
  kevin-network:
